### ISSUE TITLE
Handle types support

### ISSUE THREAD

**Issue by viciious** [Hazelight/vscode-unreal-angelscript#8]
Hi!

The support for handle types doesn't seem to be present. If variable 'bar' is of handle type 'Foo @' typing 'bar.' should bring up the intellisense/autocompletion menu but that doesn't seem to be the case. Am I missing something?

Thanks!

**Comment by GGLucas** [comment]
The UnrealEngine-Angelscript script compiler has some modifications to work within the unreal garbage collector that removes handle syntax altogether.

Whether a type is a value type or reference type is inferred by whether it derived from UObject (reference type), or not (value type), so you never type an `@` character yourself, and indeed using `@` in code compiled by the unreal plugin is a syntax error.

If you're trying to use this extension for angelscript outside of the unreal plugin, it probably won't work great for you as there are a fair amount of differences in the syntax.
